name: mini_project_warmindo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/beras/berasBasmati.jpeg
   - assets/beras/berasHitam.jpeg
   - assets/beras/berasMerah.jpeg
   - assets/beras/berasPutih.jpeg
   - assets/beras/berasCoklat.jpg
   - assets/beras/berasKetan.jpg
   - assets/logo.png
